language: php

sudo: false

matrix:
    include:
        - php: 7.0
        - php: 7.1
        - php: 7.2
    fast_finish: true

env:
    global:
        - deps=no
        - COMPOSER_OPTIONS="--prefer-stable"

install:
    - composer require --no-update ramsey/uuid ^3.0
    - composer require --no-update hidehalo/nanoid-php ^1.0
    - composer update --prefer-source

script:
    - vendor/bin/phpunit
